name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # GHCRへログイン
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up workspace
        run: |
          ls -la
          ls -la docker

      # Dockerイメージのビルドとプッシュ
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./docker
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          build-args: |
            REPO_URL=https://github.com/yutosawada/docker_sample.git
